#:kivy 2.3.1

<HabitWidget>:
    canvas:
        Color:
            rgba: 0.16, 0.32, 0.75, 1
        Rectangle:
            size: root.width,70
            pos: 0,root.height-70
    Label: 
        font_size: 20
        center_x: root.width / 2
        center_y: root.height / 2
        text: "YAAAAAAAAAAAAAAAAAAAS!"
    Label: 
        font_size: 30
        color: 0,0,0,1
        bold: True
        center_x: root.width / 2
        center_y: root.height -35
        text: "Habit Tracker!"
